#!/bin/ksh
#

. $FACTORY_ROOT/functions.logs
. $FACTORY_ROOT/functions.divers
. $FACTORY_ROOT/functions.cfg
. $FACTORY_ROOT/functions.menu

##### Init
##
## Init part, run only once
## This will set some usefull variable
##
###### Ouput:
##
## * ECHOCMD
## * HOSTNAME
## * SHORTHOSTNAME
## * PROGNAME
## * FACTORY_PLATFORM
## * FACTORY_DISTRIB
## * FACTORY_TMPDIR
## * FACTORY_TMPFILES
## * FACTORY_SUDO
##
##---

export FACTORY_PLATFORM=`uname`
case $FACTORY_PLATFORM in 
	CYGWIN*)
		export ECHOCMD="echo"
		;;
	Linux*)
		export ECHOCMD="echo"
		# Setup Linux distibution
		if [ -r /etc/SuSE-release ]
		then
			export FACTORY_DISTRIB=Suse
		elif [ -r /etc/redhat-release ]
		then
			export FACTORY_DISTRIB=RedHat
		elif [ -r /etc/debian_version ]
		then
			export FACTORY_DISTRIB=Debian
		elif [ -r /etc/mandrake-release ] 
		then
			export FACTORY_DISTRIB=Mandrake
                elif [ -r /etc/slackware-version ]
		then
		        export FACTORY_DISTRIB=Slackware
		elif [ -r /etc/knoppix_version ]
		then
			export FACTORY_DISTRIB=Knoppix
		fi
		;;
	SunOS)
		alias awk=/usr/xpg4/bin/awk
		export ECHOCMD="print"
		;;
	*)
		export ECHOCMD="print"
		;;
esac

if [[ -z "$FACTORY_CORE_FUNCTIONS" ]]
then 
	export HOSTNAME=`hostname`
	export SHORTHOSTNAME=`echo $HOSTNAME | cut -f1 -d.`
	if [ -z "$PROGNAME" ]
	then
	  case $FACTORY_PLATFORM in
		SunOS)	
			export PROGNAME=`/usr/xpg4/bin/basesename -- $0`
		;;
		*)
			export PROGNAME=`basename -- $0`
		;;
	  esac
	fi

	# seltlogenv is in functions.menu
	setlogenv

	export FACTORY_TMPDIR=/tmp
	export FACTORY_TMPFILES=$FACTORY_TMPDIR/$PROGNAME.TEMFILES.$$

	PATH=$PATH:$FACTORY_ROOT
	export PATH

	#
	# Check tty
	#

	tty -s >/dev/null 2>/dev/null
	if [ $? -ne 0 ]
	then
		FACTORY_NOTTY=1
	fi
	FACTORY_CORE_FUNCTIONS="DONE"
	export FACTORY_NOTTY
	export FACTORY_CORE_FUNCTIONS
	if [ -f /usr/bin/sudo ]
	then
		FACTORY_SUDO=/usr/bin/sudo
	elif [ -f /usr/local/bin/sudo ]
	then
		FACTORY_SUDO=/usr/local/bin/sudo
	else
		logerror "Can't find sudo command"
		exit 1
	fi
	export FACTORY_SUDO
fi
